### ISSUE TITLE
Use post call to create a new entry

### ISSUE THREAD

**Issue by lhmcgann** [lhmcgann/MyDiaryApp#24]
again tricky bc embedded document, so need to figure out how to organize insert/update diary calls
see https://docs.google.com/document/d/1GzvS6ELUQNPR1S662smtaUvlMpyAbdKVl0_K5YSTnvU/edit: look at the $push update operator which adds a document to the end of an array
time estimate: 4hrs

**Comment by lhmcgann** [comment]
db functions (save/reload) work in isolation and have been thoroughly tested. At least 3hrs (kind of included in "Figure out entry access..." issue though. Now backend needs to use these functions.

**Comment by sarbor** [comment]
Forgot to comment on this issue.

Implemented the save/reload functions in the relevant backend endpoints.

Estimate Time: 1 hr

**Comment by sarbor** [comment]
Actual time for issue: 4 hours
