### ISSUE TITLE
Delete entry from delete request

### ISSUE THREAD

**Issue by lhmcgann** [lhmcgann/MyDiaryApp#25]
again more complicated bc entries are embedded documents
time estimate: 3hrs

**Comment by lhmcgann** [comment]
5/24: spent same 1hr as described on "Figure out functions ..." issue. See [commit](https://github.com/lhmcgann/MyDiaryApp/commit/1a91483c010081dcb509b6cebd5082d356e4d2ab)

**Comment by lhmcgann** [comment]
Remove() function in model_mongo.py is fully functional. Took maybe an hr to fully test (2hrs this and above combined). This function needs to be called properly from the backend, though, and then connected to frontend.

**Comment by sarbor** [comment]
Added the remove function to the relevant backend endpoints, took approximately 30 minutes.

**Comment by sarbor** [comment]
Time Completion: 3 hours
